name: glacier-mass-balance

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - numpy
  - matplotlib
  - seaborn
  - ipykernel # for interactive notebooks
  - pathlib
  - xarray
  - rioxarray